server:
  session-timeout: 1800
  port: 80
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mybatis/*Mapper.xml
  typeAliasesPackage: com.lwy.bootws.bean
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bootws?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    initialSize: 1
    minIdle: 3
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # useGlobalDataSourceStat: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-confirms: true  #  消息发送到交换机确认机制,是否确认回调
    publisher-returns: true
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 10000ms
    jedis:
      pool:
        # 最大空闲数
        max-idle: 8
        # 最小
        min-idle: 10
        # 最大连接数
        max-active: 100
        # 最大阻塞等待时间
        max-wait: -1
